#!/bin/sh

GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

echo
echo -e "${GREEN}Updating ${BLUE}$(hostname)${GREEN}...${NC}"
echo

sudo guix system --load-path=/home/Ez3/src/Guix/configurations reconfigure ~/src/Guix/configurations/daviwil/systems/$(hostname).scm
